# Site settings
title: PhD Candidate Landing Page
description: >-
  A landing page for a PhD candidate developing an XRD prototype analyzer.
baseurl: ""
url: ""
github_username: jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
